### ISSUE TITLE
Header Error

### ISSUE THREAD

**Issue by netin1202** [stefan-prokop-cz/verify-apple-id-token#98]
Hi, 
I am getting error  "Cannot read property 'header' of null". Where I need to send headers.

**Comment by stefanprokop** [comment]
Hi @netin1202 

thank you for you report! Can you please show me some further information? The version, minimal working example, the error line in the package - where the error appeared and so on, thank you :slightly_smiling_face:

**Comment by netin1202** [comment]
const apple = async (token) => {
    try {
        const jwtClaims = await verifyAppleToken({
            idToken: "001674.b31315815467...............",
            clientId: "5L49......"
        });
        return jwtClaims;
    } catch (err) {
        throw err;
    }
};



I am using this code. I have made a API to access this function.

**Comment by stefanprokop** [comment]
Thanks!

Do you know what is the `idToken` (the `001674.b31315815467...`)? Because it looks to me that it is not a valid JWS E256 format or is it. :thinking: You can try to verify it here: https://jwt.io/

Because if you look at the apple developer docs here is the authentication process: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user and there is something called grant code https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens (`Validate the Authorization Grant Code` the `code`) and my question is if the token is really id token from the authentication process link or the code from the grant code link? Can you please make sure you have a correct id token? :pray:

**Comment by netin1202** [comment]
Thank You, 
yes, idToken was wrong in this case.
